name: farmtopia_task
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  google_maps_flutter: ^2.5.0
  get: ^4.6.6
  uuid: ^4.1.0
  cloud_firestore: ^4.9.2

   
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
